[tool.black]
line-length = 120
target_version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv
    | _build
    | buck-out
    | build
    | dist
    | server/common/fbs/NetEncoding
  )/

)
'''

[tool.poetry]
name = "cellxgene"
version = "0.1.0"
description = ""
authors = ["Ivo Leist <ivo.leist@googlemail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
anndata="^0.7.6"
boto3="^1.12.18"
click="^7.1.2"
Flask="^1.0.2"
Flask-Compress="^1.4.0"
Flask-Cors="^3.0.9"
Flask-RESTful="^0.3.6"
flask-server-timing="^0.1.2"
flask-talisman="^0.7.0"
flatbuffers="^1.11.0"
flatten-dict="^0.2.0"
fsspec="^0.6.0"
gunicorn="^20.0.4"
h5py="^3.0.0"
numba="^0.51.2"
numpy="^1.17.5"
packaging="^20.0"
pandas="1.1.1"
PyYAML="^5.4"
scipy="^1.4"
requests="^2.22.0"
s3fs="0.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
